### ISSUE TITLE
ゴールしたのに残り2.0kmと表示される

### ISSUE THREAD

**Issue by kaibadash** [SuzukaHori/YamaNotes#198]
ゴールしたのに残り2.0kmと表示される。手元で早すぎるペースでゴールしたからかも？
<img width="372" alt="image" src="https://github.com/user-attachments/assets/1f547547-a3f5-4e7b-bf82-94057275abf7">

**Comment by SuzukaHori** [comment]
@kaibadash 
バグ報告ありがとうございます！再現確認しました😭
タスクとして追加したので、後ほど修正します🙇‍♀️

**Comment by SuzukaHori** [comment]
修正完了したのでクローズします。
ご報告ありがとうございました🙇‍♀️🙇‍♀️
