### ISSUE TITLE
DB設計をする

### ISSUE THREAD

**Issue by SuzukaHori** [SuzukaHori/YamaNotes#3]
レビューをよろしくお願いいたします🙇‍♀️

- エレベーターピッチ
https://bootcamp.fjord.jp/products/18745

- ペーパープロトタイプ
https://bootcamp.fjord.jp/products/19196

- リソース設計
[リソース設計をする #31](https://github.com/SuzukaHori/YamaNotes/issues/31#issuecomment-1991200287)

- DB設計
[DB設計をする #3](https://github.com/SuzukaHori/YamaNotes/issues/3#issue-2175740785)

- 技術構成
Rails（+ Hotwire）で実装予定です。
[フレームワーク・プラットフォームを選定する#14](https://github.com/users/SuzukaHori/projects/4?pane=issue&itemId=55967936)

### ER図

```mermaid
erDiagram
  Users ||--|| Walks: "1人のユーザーは1つの歩行を持つ"
  Arrivals }|--|| Stations: "1つの駅は複数の到着を持つ"
  Walks||--|{ Arrivals: "1つの歩行は複数の到着を持つ"


  Users {
    integer uid PK
    string provider
  }

  Walks{
    integer id PK 
    integer user_id FK
    boolean publish
    boolean clockwise
  }

  Arrivals {
    integer id PK
    integer walk_id FK 
    integer station_id FK 
    string memo
    datetime arrived_at
  }

  Stations {
    integer id PK
    string name
    float longitude
    float latitude
    float clockwise_distance_to_next
    integer clckwise_next_station_id FK
  }
```

### データ表
- Users

|id |name |
|---|---|
|1 |すずか |
|2 |ピヨルド |

- Walks

|id |user_id | publish | clockwise| 
|:---:|:---:|:---:|:---:|
|1 | 1|  false | true | 
|2 | 2|  true | false | 

- Arrivals

|id |walk_id | station_id  | memo| arrived_at |
|:---:|:---:|:---:|:---:|:---:|
|1 | 1|1 | 出発しました！今日は頑張ります。 | 2023/03/13/19:00|
|1 | 2 |10 | 疲れてきてクタクタです。 | 2023/03/14/0:00|

- Stations

|id |name | longitude  |  latitude | clockwise_distance_to_next |  clckwise_next_station_id|
|:---:|:---:|:---:|:---:|:---:|:---:|
|1 | 渋谷| 35.65773 |139.70323 | 1.4 | 2 |
|2 | 原宿 |  35.6684 |139.70514 | 2.5  | 3 |

<details><summary> 2回目の提出物</summary>

### ER図

```mermaid
erDiagram
  Users ||--|| Walks: "1人のユーザーは1つの歩行を持つ"
  Arrivals }|--|| Stations: "1つの駅は複数の到着を持つ"
  Walks||--|{ Arrivals: "1つの歩行は複数の到着を持つ"

  Users {
    integer uid PK
    string provider
  }

  Walks{
    integer id PK 
    integer user_id FK
    boolean publish
    boolean clockwise
  }

  Arrivals {
    integer id PK
    integer walk_id FK 
    integer station_id FK 
    string memo
    datetime arrived_at
  }

  Stations {
    integer id PK
    string name
    float longitude
    float latitude
    float clockwise_distance_to_next
    float counterclockwise_distance_to_next
  }
```

### データ表
- Users

|id |name |
|---|---|
|1 |すずか |
|2 |ピヨルド |

- Walks

|id |user_id | publish | clockwise| 
|:---:|:---:|:---:|:---:|
|1 | 1|  false | true | 
|2 | 2|  true | false | 

- Arrivals

|id |walk_id | station_id  | memo| arrived_at |
|:---:|:---:|:---:|:---:|:---:|
|1 | 1|1 | 出発しました！今日は頑張ります。 | 2023/03/13/19:00|
|1 | 2 |10 | 疲れてきてクタクタです。 | 2023/03/14/0:00|

- Stations

|id |name | longitude  |  latitude | clockwise_distance_to_next | counterclockwise_distance_to_next|
|:---:|:---:|:---:|:---:|:---:|:---:|
|1 | 渋谷| 35.65773 |139.70323 | 1.4 | 2.0 |
|2 | 原宿 |  35.6684 |139.70514 | 2.5  | 1.4 |

</details>

<details><summary>1回目の提出物</summary>

### ER図

```mermaid
erDiagram
  Users ||--|| Walks: "1人のユーザーは1つの歩行を持つ"
  Arrivals }|--|| Stations: "1つの駅は複数の到着を持つ"
  Walks||--|{ Arrivals: "1つの歩行は複数の到着を持つ"

  Users {
    integer uid PK
    string provider
  }

  Walks{
    integer id PK 
    integer user_id FK
    boolean publish
    boolean clockwise
  }

  Arrivals {
    integer id PK
    integer walk_id FK 
    integer station_id FK 
    string memo
    datetime arrived_at
  }

  Stations {
    integer id PK
    string name
    float longitude
    float latitude
    float distance_to_next
  }
```
- Userテーブルのuidとproviderは、Googleの認証を作る際に必要なカラムです。
deviseとomniauthで実装予定です。

-  Walksテーブルのclockwise（時計回り）は「内回りor外回り」を表しています。trueなら外回り・falseなら内回りです。

- Stationsテーブルのdistance_to_nextは次の駅までの歩行距離です。
緯度・経度から直線距離は計算できるのですが、ユーザが知りたいのは歩いた時の距離だと考えました。緯度・経度から歩行距離を求めるには、有料のAPIが必要なようなので、可能であればデータベース上に持たせたいです。
ただ、内回り・外回りを切り替えると「次の駅」が変わってしまい処理がややこしくなりそうなので、もっと良い方法があれば教えていただきたいです🙇‍♀️

- UsersとWalksが一対一の関係になっていますが、いずれは一人が何周も記録できるように機能追加したいです。

### データ表
- Users

|id |name |
|---|---|
|1 |すずか |
|2 |ピヨルド |

- Walks

|id |user_id | publish | clockwise|
|:---:|:---:|:---:|:---:|
|1 | 1|  false | true |
|2 | 2|  true | false |

- Arrivals

|id |walk_id | station_id  | memo| arrived_at |
|:---:|:---:|:---:|:---:|:---:|
|1 | 1|1 | 出発しました！今日は頑張ります。 | 2023/03/13/19:00|
|1 | 2 |10 | 疲れてきてクタクタです。 | 2023/03/14/0:00|

- Stations

|id |name | longitude  |  latitude | distance_to_next |
|:---:|:---:|:---:|:---:|:---:|
|1 | 渋谷| 35.65773 |139.70323 | 1.4 |
|2 | 原宿 |  35.6684 |139.70514 | 2.5  |

</details>

**Comment by maedana** [comment]
> 内回り・外回りを切り替えると「次の駅」が変わってしまい処理がややこしくなりそうなので、もっと良い方法があれば教えていただきたいです🙇‍♀️

シンプルに内回りのときの次の駅、外回りのときの次の駅の距離をそれぞれ別カラムに持ってしまうのはいかがでしょうか?`distance_to_next`を2種類持つ感じですね。

**Comment by maedana** [comment]
walksに出発的の設定がいるんじゃないですかね?

**Comment by SuzukaHori** [comment]
レビューありがとうございます！
修正しましたので、再度確認をお願いします。https://github.com/SuzukaHori/YamaNotes/issues/3#issue-2175740785

変更点：
- Usersテーブルに`clockwise_distance_to_next`と`counterclockwise_distance_to_next`を追加しました。

出発駅については、初期設定画面で「はじめる」を押した時に`arrived_at`が`nil`のarrivalが追加されるイメージで考えました。
よろしくお願いいたします🙇‍♀️

**Comment by SuzukaHori** [comment]
お疲れ様です。
Stationsテーブルの設計を微修正したいと考えているので、アドバイスをお願いしたいです🙇‍♀️

変更したいこと：
- `clckwise_next_station_id`を追加したい。
先日日報でご指摘いただいた通り、駅同士の位置関係が、駅の登録順に依存するのが良くないと思ったためです。
- `counterclockwise_distance_to_next`を削除したい。
理由は以下の通りです。
  - 駅間の距離は内回り・外回りで同じなので、同じ距離を複数のカラムで持つのは冗長だと感じたため。
  - 内回りの時のみ条件分岐させれば、そこまで複雑にならず実装できそうな気がしたため。
 
考えた日の日報：https://bootcamp.fjord.jp/reports/92506#-2

変更内容についてご意見をいただきたいです。よろしくお願いいたします🙏

**Comment by maedana** [comment]
言われてみれば確かに内回り、外回りのそれぞれのカラムを持たなくても実現できそうですね。書かれている内容でやってみましょう! 当初のレビューの段階で気がつけたらよかったんですが、そこまで考えが及びませんでした :pray:

**Comment by SuzukaHori** [comment]
ご確認ありがとうございます！こちらで進めたいと思います😊

日報にコメントくださってありがたかったです🙏今後も迷ったら相談をさせてください🙇‍♀️
