### ISSUE TITLE
リソース設計をする

### ISSUE THREAD

**Issue by SuzukaHori** [SuzukaHori/YamaNotes#31]
レビューをお願いします🙇‍♀️
- エレベーターピッチ
https://bootcamp.fjord.jp/products/18745

- ペーパープロトタイプ
https://bootcamp.fjord.jp/products/19196

- DB設計
[DB設計をする #3](https://github.com/SuzukaHori/YamaNotes/issues/3#issue-2175740785)

- 技術構成
Rails（+ Hotwire）で実装予定です。
[フレームワーク・プラットフォームを選定する#14](https://github.com/users/SuzukaHori/projects/4?pane=issue&itemId=55967936)

#### 4回目の提出物

|  Method  |  Path  | Description | 
| :---: | ---| ------| 
| GET  | /  | トップページ  |statics#home
| GET |  /walk/new | 初期設定画面（出発駅設定・内回り外回りを登録画面）を表示 |
| POST | /walk | 出発駅・内回り外回りを登録し、walksを作る |
| GET | /walk| メイン画面・地図や進捗を表示する |
| PUT | /walk | 履歴の公開範囲を編集する |
| DELETE | /walk | リタイアして全ての記録を削除する |
| GET | /users/:id/arrivals  | ゲスト用の到着履歴一覧画面を表示する|
| GET |/arrivals | 本人用の到着履歴一覧画面を表示する |
| POST| /arrivals | 各駅の到着時間及びメモを記録する |
|GET| /arrivals/:id | 各駅の到着詳細画面を表示する |
| PUT | /arrivals/:id  | 到着時間・メモを編集する |
| DELETE | /arrivals/:id  | 到着時間およびメモを削除する |
| GET | /terms  | 利用規約・プライバシーポリシーを表示する | 
| POST | /users/auth/google_oauth2 | ログインする |
| POST | /logout| ログアウトする |

<details><summary>3回目の提出物</summary>

|  Method  |  Path  | Description | 
| :---: | ---| ------| 
| GET  | /  | トップページ  |statics#home
| GET |  /walk/new | 初期設定画面（出発駅設定・内回り外回りを登録画面）を表示 |
| POST | /walk | 出発駅・内回り外回りを登録し、walksを作る |
| GET | /walk| メイン画面・地図や進捗を表示する |
| PUT | /walk | 履歴の公開範囲を編集する |
| DELETE | /walk | リタイアして全ての記録を削除する |
| GET | /users/:id/arrivals  | ゲスト用の到着履歴一覧画面を表示する|
| GET |/arrivals | 本人用の到着履歴一覧画面を表示する |
| POST| /arrivals | 各駅の到着時間及びメモを記録する |
|GET| /arrivals/:id | 各駅の到着詳細画面を表示する |
| PUT | /arrivals/:id  | 到着時間・メモを編集する |
| DELETE | /arrivals/:id  | 到着時間およびメモを削除する |
| GET | /terms  | 利用規約・プライバシーポリシーを表示する | 
| POST | /users/auth/google_oauth2 | ログインする |
| POST | /logout| ログアウトする |

</details>

<details><summary>2回目の提出物</summary>

|  Method  |  Path  | Description | 
| :---: | ---| ------| 
| GET  | /  | トップページ  |statics#home
| GET |  /walks/new | 初期設定画面（出発駅設定・内回り外回りを登録画面）を表示 |
| POST | /walks | 出発駅・内回り外回りを登録し、walksを作る |
| GET | /walks| メイン画面・地図や進捗を表示する |
| PUT | /walks | 履歴の公開範囲を編集する |
| DELETE | /walks | リタイアして全ての記録を削除する |
| GET | /users/:id/arrivals  | 到着履歴一覧画面を表示する|
| POST| /arrivals | 各駅の到着時間及びメモを記録する |
|GET| /arrivals/:id | 各駅の到着詳細画面を表示する |
| PUT | /arrivals/:id  | 到着時間・メモを編集する |
| DELETE | /arrivals/:id  | 到着時間およびメモを削除する |
| GET | /terms  | 利用規約・プライバシーポリシーを表示する | 
| POST | /users/auth/google_oauth2 | ログインする |
| POST | /logout| ログアウトする |

</details>

<details><summary>1回目の提出物</summary>

|  Method  |  Path  | Description |
| :---: | ---| ---| 
| GET  | /  | トップページ  |
| GET |  /settings | 初期設定画面を表示 |
| GET | /map | メイン画面・地図や進捗を表示する |
| POST | /map  | 出発駅・内回り外回りを登録する |
| GET| /records | 到着履歴一覧画面を表示する |
| POST| /records  | 到着した時間及びメモを記録する |
| DELETE | /records  | リタイアして全ての記録を削除する |
| PUT | /records/:id  | 到着時間・メモを編集する |
| DELETE | /records/:id  | 到着時間およびメモを削除する |
| GET | /arrival  | 到着ページを表示する|
| PUT | /publish  | 履歴の公開範囲を編集する |
| GET | /terms  | 利用規約・プライバシーポリシーを表示する |
| POST | /google_login_api/callback| ログインする |
| POST | /logout| ログアウトする |

</details>

**Comment by SuzukaHori** [comment]
|  Method  |  Path  | Description |
| :---: | :---:|  :---:| 
| GET  | /  | トップページ  |
| GET | /map | メイン画面（地図） |
| GET |  /map/new | 地図の初期設定画面 |
| POST | /map  | 出発駅・内回り外回りを登録する |
| POST| /arrivals  | 到着時間記録 |
| GET| /arrivals | 到着履歴画面 |
| GET | /arrivals/new  | 「到着しました」の画面|
| PUT | /arrivals  | 到着時間・メモ・編集 |
|  POST |/arrivals/memo| メモの追加 |
| PUT | /retirements  | リタイア |
| GET | /terms  | 利用規約・プライバシーポリシーを表示 |

**Comment by maedana** [comment]
- 初期設定の「はじめる」ボタンを押したときにwalksが1件作られるイメージかと思いましたが、そのためのルーティングがないかなーと思いました。
-「到着」をクリックのときは`GET	/arrival	到着ページを表示する`なのだと思いますが、arrivalsを1件作るのでしょうし、REST的には`POST /arrivals`が自然かなーと思います。その上で特定の到着ページとなると`GET /arrivals/:id`が自然で、`POST /arrivals`したときのリダイレクト先になるかなと。到着関連が原則`records`になってますけど、強いこだわりがなければDBにあ合わせて`arrivals`で揃えるといいんじゃないですかね
- 到着関連ですが、特定の歩行(walks)に紐付けくわけですよね。現在の歩行はどうやって特定する想定ですか? URIにないので何か別の手段で特定する必要があるかと思いますが、簡単でお手軽なのはURLに含めておくことかなーと思います。簡単なのは例えば、/walks/:walk_id/arrivals/:id が特定の到着を示すようにするような感じでDBの階層構造をそのままURIで表現する感じかなーと。なにかこだわりがあってURLを短くしたいということがなければ素直なURI構造の方がいいんじゃないかなと思います。
- 履歴の公開についても対象となるデータはwalksに持ってますが、`/publish`なので、対象となるwalkはURIに入ってないですし、到着関連と同じことが言えそうですね。

**Comment by SuzukaHori** [comment]
@maedana 
レビューありがとうございます🙏
全体的に大幅に修正しましたので、お手数ですが再度ご確認をお願いします🙇‍♀️https://github.com/SuzukaHori/YamaNotes/issues/31#issue-2178168774

修正点は以下の通りです。

- データベース名（walks・arrivals）とURLを揃えるようにしました。
- walks関連のURLを修正しました。
本来なら`walks/:id`となる箇所が複数ありますが、現在WalksとUserは一対一で考えているため`walks`としました。
- 履歴一覧ページで、誰の歩行かを判定できるようuser_idをURLに含めました。
他の`arrivals`を含むページについては、ログインを前提としているため、パスにuser_idを入れていません。
ただ、一つだけuser_idを含むパスがあるのに少し違和感があります💦

**Comment by maedana** [comment]
> walks関連のURLを修正しました。
本来ならwalks/:idとなる箇所が複数ありますが、現在WalksとUserは一対一で考えているためwalksとしました。

1:1なので複数形でなくて単数形でいいかなーと思います。routes.rbに書く際も単数形の`resource`を使えばよいかなと。ただ、将来複数のwalksをuserが持つことを見据えるなら、URIは最初から`本来ならwalks/:idとなる`設計にしておくのもありかもしれません。そうでないといずれURI設計が変わってしまいますしね。

> ただ、一つだけuser_idを含むパスがあるのに少し違和感があります💦

公開用と本人用で二種類あってもいいと思いますよ。公開用が`GET	/users/:id/arrivals	到着履歴一覧画面を表示する`で、本人用に別途`GET /arrivals`がある、みたいな。

**Comment by SuzukaHori** [comment]
レビューありがとうございます🙏

> 1:1なので複数形でなくて単数形でいいかなーと思います。routes.rbに書く際も単数形のresourceを使えばよいかなと。

単数形のresourceの存在を知りませんでした、勉強になりました😳最初から`walks/:id`の形にしておくことも考えましたが、複数持てない状態でメイン画面が`/walks/1`となるのが気持ち悪かったので、一旦`walk`で実装を進めようと思います🙇‍♀️

到着履歴一覧画面については、本人用`/arrivals`と`/users/:id/arrivals`に分ける形で進めようと思います！

**Comment by SuzukaHori** [comment]
一点追加で質問させていただきます🙇‍♀️

メイン画面で全ての駅にピンを立てて緑の線を引くため、Stimulusで全駅のデータを取得する必要があることに気づきました。
一旦、`/sations`にgetリクエストを送る（stations#index）とデータがJsonで返ってくる形で実装したので、URI設計に追加しました。https://github.com/SuzukaHori/YamaNotes/issues/31#issue-2178168774

この場合は`/api/stations`としたほうがいいのでしょうか？？このような形の実装が初めてなので、伺いたいです🙇‍♀️

**Comment by SuzukaHori** [comment]
ご返信ありがとうございます！
公開する場合としない場合で、URLが違うのですね😳！勉強になりました。

> ちなみにstimulusにデータ渡したいだけならrouting追加せずともviewにstimulusのValueとしてStation.all.to_json的なものを突っ込んでしまってもいいかなと思います。

一箇所しか使用していないので、これがまさに私のやりたいことでした🙏いただいた資料をもとに、ルーティングを追加しない形に修正しようと思います！
